name: Reusable Build Workflow Demo
on: workflow_dispatch
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js 22
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js 22
              uses: actions/setup-node@v4
              with:
                node-version: 22
            
            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    build:
        uses: ./.github/workflows/resuable-build-workflow.yml

    deploy:
        runs-on: ubuntu-latest
        needs: [build, lint, test]
        steps:
            - name: Deploy application
              run: echo "Deploying application... with build status ${{ needs.build.outputs.build-status }}"